# Generated by Django 2.0.2 on 2018-04-30 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.TimeField(default=datetime.datetime(2018, 4, 30, 9, 37, 21, 221515, tzinfo=utc)),
        ),
    ]
